### ISSUE TITLE
Encoding issues in Nix install unless `LC_ALL` is set

### ISSUE THREAD

**Issue by haoyun** [srid/emanote#125]
**Describe the bug**
I have a markdown file with file name in CJK characters.
The generated html has name `������.html`. Also in terminal,
```
[Debug#WS.Client.01]  ~~> Identity (Identity (Identity R[LMLType Md]:������))
```

**To Reproduce**
1. newly created project folder with only one file: `测试.md`
2. run `emanote`

**Expected behavior**
In terminal and browser, Chinese characters should be properly displayed.

**Desktop (please complete the following information):**
 - Browser Chrome
 - Version latest

**Comment by srid** [comment]
It works for me:

![image](https://user-images.githubusercontent.com/3998/133103837-7434e1c8-d039-45fb-bd75-047bb0485dec.png)

![image](https://user-images.githubusercontent.com/3998/133103902-8a3d8137-46d4-4476-8b29-e5363b327e43.png)

![image](https://user-images.githubusercontent.com/3998/133104419-9ffc5f6b-5086-4c53-8775-66e1e11b60c3.png)

---

But I wonder what we can do here to make it behave consistently regardless of the user environment. What happens when you run emanote with `LANG=C.UTF-8` and/or `LC_ALL=C.UTF-8`? See https://github.com/srid/emanote/discussions/120#discussioncomment-1255160

**Comment by haoyun** [comment]
Thanks for the information. With `LC_ALL=C.UTF-8`, it works.

Then it seems to be a nix problem. It reminds me of a similar problem with hledger https://github.com/simonmichael/hledger/issues/1033#issuecomment-497940396.

**Comment by srid** [comment]
Could you paste the output of `env | grep LC` and `env | grep LANG`? Just curious what your user environment already defines.

**Comment by haoyun** [comment]
```
~/Documents/emanote ❯ env | grep LC 

~/Documents/emanote ❯ env | grep LANG
GDM_LANG=en_US.utf8
LANG=en_US.utf8
```

**Comment by srid** [comment]
Probably related: https://github.com/srid/neuron/issues/381

The only pending question I guess is whether Emanote should set `LOCALE_ARCHIVE` as part of its nix derivation.
