### ISSUE TITLE
Toggle-able sidebar

### ISSUE THREAD

**Issue by srid** [srid/emanote#13]
Change the HTML template to improve navigation on mobile. Around here,

https://github.com/srid/emanote/blob/78c9a2cf39d20fd90015e810b6d244cc270df49e/default/templates/layouts/book.tpl#L25-L28

- [ ] In mobile view (where sidebar currently remains always hidden), display the burger menu on top, clicking which toggles the sidebar visibility

Inspiration / example: https://web.dev/learn/css/flexbox/

**Comment by srid** [comment]
Perhaps we should make the burger menu visible on desktop as well, allowing (momentary) hiding of sidebar to get more width for main content. https://rust-lang.github.io/mdBook/index.html does this.

**Comment by carliros** [comment]
I like that rust page, it will definitely provide more space. I also how they let the user change themes for the page. I would like that to be added as well.

**Comment by carliros** [comment]
@srid,
in order to have something similar to that Rust page, we will need some restructure on our templates
1. Create a top nav bar to contain the icon to show/hide sidebar
2. Attach in current page title the icon to show/hide sidebar

Another alternative would be to attach this show/hide button in the breadcrumb that is show only in small screens.

What do you think about this?

**Comment by srid** [comment]
@carliros I'd start with a "minimum viable product" that basically works, even if it will look ugly. So I'd say that the alternative approach (of piggybacking on breadcrumbs) would be a good start. 

This would involve JavaScript right? Once we have the basic user interaction (UX) working, we can tweak the CSS/HTML design later (and see how the UI can be integrated on desktop view and the neuron view of #22).
