### ISSUE TITLE
pandoc.rewriteClass doesn't apply to links

### ISSUE THREAD

**Issue by rvl** [srid/emanote#184]
### Describe the bug

I would like to style several links on a page with the same set of tailwind css class.

So instead of this:
```
[[README]]{class="hover:no-underline bg-green-100 text-green-700 font-bold text-3xl"}
```
I want this:
```
[[README]]{class="mylink"}
```
Using config:
```yaml
pandoc:
  rewriteClass:
    mylink: hover:no-underline bg-green-100 text-green-700 font-bold text-3xl
```

It doesn't seem to work though.

### To Reproduce

Replace `emanote-template/index.md` with the following:
```
---
pandoc:
  rewriteClass:
    mylink: hover:no-underline bg-green-100 text-green-700 font-bold text-3xl
---

# Emanote Template

## Testing stuff {#heading .mylink}

[[README|1. inline - no class]] - a plain link

[[README|2. inline - tailwind classes]]{#expected class="hover:no-underline bg-green-100 text-green-700 font-bold text-3xl"} - desired appearance, but the tailwind class lists are duplicated.

[[README|3. inline - mylink class]]{#actual class="mylink"} - rewriteClass

Example of a span with [4. rewriteClass]{.mylink}.

{#before-block .mylink}
[[README|5. outer block - mylink class]] - this is almost correct, but adds an outer div.

[[README|6. para block - mylink class]]
{#after-block .mylink}
```

### Expected behavior

I would like example 3 to appear the same as example 2 above.

So the resulting `<a>` element should not have `class="mylink ..."`, and should instead have all the classes defined in the `pandoc.rewriteClass.mylink` YAML config.

### Actual

Classes applied to link elements followed by Commonmark attributes do not get rewritten with `pandoc.rewriteClass` rules.

### Screenshots

![image](https://user-images.githubusercontent.com/1019641/139567120-f89bab72-8d8f-477a-9ec0-ba4daeb42bc8.png)

### Desktop
 - Browser: Chromium Version 94.0.4606.54

### Additional context

- emanote rev: 71abc42e29b3355a0acdce922cf1bf53a64e12bb
- emanote-template rev: e02f284858a5da2afd996598ccd79b519c804d25

Thanks!

**Comment by srid** [comment]
This works as a workaround

```markdown
[[[guide]]]{.mylink}
```

This is same as your span example (number 4) except we use a wiki-link instead of plain text in the span body. In fact, you can use just about any Markdown syntax in the span.

---

Okay, back to the issue itself, I suspect this is a matter of fixing it in our commonmark parser extensions, possibly in the wiki-link parser here:

https://github.com/srid/emanote/blob/fd2d1cf401d04ac51adb4fbdb6248c89057fc133/src/Emanote/Pandoc/Markdown/Syntax/WikiLink.hs#L179-L188

or somewhere in commonmark configuration here (perhaps something to do with ordering of exts?):

https://github.com/srid/emanote/blob/fd2d1cf401d04ac51adb4fbdb6248c89057fc133/src/Emanote/Pandoc/Markdown/Parser.hs#L20-L49

**Comment by rvl** [comment]
Thanks @srid, from my testing I found that `[[[guide]]]{.mylink}` still wraps the `<a>` inside another element, which is `<span>`, and the container element gets the `.mylink` styling rather than the `<a>` itself.

If I get any time, I will look at the modules you referenced and try to fix it, but at the moment I'm rather short on time.

**Comment by rvl** [comment]
I believe I misunderstood which elements `pandoc.rewriteClass` is supposed to apply to.

In [`default/index.yaml`](https://github.com/srid/emanote/blob/d8f1ac3664cb4ca6152e65df7362cc805e4b99b5/emanote/default/index.yaml#L47-L48) it says Div and Span.

So there is no bug - it works as specified.
