### ISSUE TITLE
Deemphasize external link icons

### ISSUE THREAD

**Issue by srid** [srid/emanote#374]
After having deployed a few sites with the new emanote, I realized that I find the external link icons (https://emanote.srid.ca/guide/html-template/external-links) a bit distracting. We should de-emphasize it somehow. Maybe by reducing the icon size.

**Comment by kukimik** [comment]
In https://github.com/EmaApps/emanote/pull/189#issuecomment-962487499 you suggested to use gray instead of the theme color to de-emphasize the icons. But I'm not sure if this really works. We introduce a new color for the icon (even if it is gray) for a single object in the middle of the text. Try using the gray color theme. In my opinion gray icons + gray color theme are less distracting than gray icons + non-gray color theme.

**Comment by kukimik** [comment]
> Try using the gray color theme.

To be clear: this is not a proposed solution to the problem. I just wanted to illustrate that introducing an extra color may be distracting.

**Comment by srid** [comment]
> In [#189 (comment)](https://github.com/EmaApps/emanote/pull/189#issuecomment-962487499) you suggested to use gray instead of the theme color to de-emphasize the icons. But I'm not sure if this really works. We introduce a new color for the icon (even if it is gray) for a single object in the middle of the text. Try using the gray color theme. In my opinion gray icons + gray color theme are less distracting than gray icons + non-gray color theme.

Yea, that's a fair point. I haven't gotten a chance to look at this yet ...

**Comment by srid** [comment]
How do we properly reduce the icon size? Changing the `height` property of svg works, but it lowers the icon itself (making it no longer a superscript).
<img width="328" alt="image" src="https://user-images.githubusercontent.com/3998/204150143-8ae35b83-801a-4c59-bf45-100469f7d671.png">

**Comment by srid** [comment]
@kukimik Where did you get the value of the `d` attribute from?

https://github.com/EmaApps/emanote/blob/3300092d40c9092e33a6b22e53a30a2a82796138/default/templates/base.tpl#L55
