### ISSUE TITLE
Twitter social preview

### ISSUE THREAD

**Issue by srid** [srid/emanote#468]
https://socialsharepreview.com/?url=https://nixos.asia/en/direnv =>

<img width="597" alt="image" src="https://github.com/srid/emanote/assets/3998/e3eacd5c-eef1-4200-bb8a-a11be8e21a4c">

**Comment by srid** [comment]
And what's going on here with the broken image render:

<img width="786" alt="image" src="https://github.com/srid/emanote/assets/3998/5e9c229b-17a4-4c2b-86fa-79eae72e7acc">

**Comment by shivaraj-bh** [comment]
`og:image` does work even on twitter, according to the [developer guidelines](https://developer.twitter.com/en/docs/twitter-for-websites/cards/guides/getting-started), they do fallback to `og:image` if  there are no tags that twitter supports. You can see that in action here: https://socialsharepreview.com/?url=https://docusaurus.io/docs/blog

And since we already support `og:image` `meta` tag after this [PR](https://github.com/srid/emanote/pull/297), we should see the image render, i.e if we have a regular URL on the page.

Regarding the broken image render above, it might be because there is a `meta` tag with empty content.
<img width="395" alt="Screenshot 2023-12-20 at 8 07 20 PM" src="https://github.com/srid/emanote/assets/23645788/0d19e7c6-44a6-4023-8e56-adbd19e9f386">

Maybe we could have a default image set in `index.yaml` as a fallback for every page.

**Comment by srid** [comment]
Ah, so basically we need to address this FIXME then:

<img width="532" alt="image" src="https://github.com/srid/emanote/assets/3998/7ccb6be7-4504-4abe-94bb-c15d71365ce0">

https://github.com/srid/emanote/pull/297/files#diff-08d291239412fde72df0c777f60d24bd5a0f802a1a8dde42e80e40499af7fabcR277-R278

That's why the image in https://nixos.asia/en/tutorial/nixos-install is not showing up.

**Comment by srid** [comment]
Preview is super bad. The 'description' itself is messed up. I will take a look.

<img width="736" alt="image" src="https://github.com/srid/emanote/assets/3998/e4dbf214-3813-49ba-adbd-0622ea806464">

**Comment by srid** [comment]
#499 addresses this, but you still have to explicitly specify the image URL in `page.image` YAML property.
