### ISSUE TITLE
Allow Markdown in title

### ISSUE THREAD

**Issue by danymat** [srid/emanote#62]
Hello, I used neuron until I discovered ema today, and I have some questions, for that I will create specific discussions for each. The first one is this:

- I sometimes use links to a footnote directly in the H1 tag on top of file, like this note:

```
# 202103151219 Le développement économique de la Chine a reconfiguré les inégalités au niveau mondial[^1]
#inégalités #gomart2021 

Seule l'Inde paraît en mesure de créer un résultat similaire dans le futur.

[^1]: Gomart, Thomas. 2021. _Guerres invisibles: nos prochains défis géopolitiques_. (Chapitre 4)
```

The problem is that this note is generated as this:

<img width="993" alt="Capture d’écran 2021-06-13 à 23 19 35" src="https://user-images.githubusercontent.com/5306901/121822156-d32ff780-cc9d-11eb-9513-9458178c4fa0.png">

The idea is to view the rendered page as something like neuron is used to do:

<img width="698" alt="Capture d’écran 2021-06-13 à 23 20 13" src="https://user-images.githubusercontent.com/5306901/121822174-e93db800-cc9d-11eb-9180-6490d3dc4aef.png">

**Comment by srid** [comment]
Yea, this can be supported. 

Emanote currently strips out the first heading from pandoc, and then substitutes it with its title property (which, in the absence of a level-1 heading, could be derived from filename or frontmatter property). 

https://github.com/srid/emanote/blob/002fe8bec5721ed2efe3a62db56e7a226e332651/src/Emanote/View/Template.hs#L123-L124

But I suppose we should track the original heading AST, instead of discarding it away - and then use it to render the title in those cases where the note does specify one (most of my notes don't specify a H1 title, because I use the filename as title).

**Comment by srid** [comment]
> Allow Markdown in title

Doing this (i.e, using Pandoc AST in note titles) should also automatically cover #57
